# -*- coding: utf-8 -*-
"""recursiveRepetitionOfString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBX5Wg9bPzQYnJfmwlYk_1JzIiijBzdn
"""

#Problem statement: Write a function that creates a recursive function that takes two parameters and repeats the string n number of times. The first parameter txt is the string to be repeated and the second parameter is the number of times the string is to be repeated.

#Problem Link: https://edabit.com/challenge/QKmETue6fMTdcB8Rq

def repeat(a, n):
  if n == 0:
    print(a*n)
  else:
    print(a*n)
    repeat(a, n-1)